# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import currency_converter_pb2 as currency__converter__pb2


class CurrencyConverterStub(object):
    """The CurrencyConverter service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.unary_unary(
                '/currencyconverter.CurrencyConverter/Convert',
                request_serializer=currency__converter__pb2.ConversionRequest.SerializeToString,
                response_deserializer=currency__converter__pb2.ConversionResult.FromString,
                )


class CurrencyConverterServicer(object):
    """The CurrencyConverter service definition.
    """

    def Convert(self, request, context):
        """Converts an amount between two currencies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurrencyConverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=currency__converter__pb2.ConversionRequest.FromString,
                    response_serializer=currency__converter__pb2.ConversionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'currencyconverter.CurrencyConverter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CurrencyConverter(object):
    """The CurrencyConverter service definition.
    """

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/currencyconverter.CurrencyConverter/Convert',
            currency__converter__pb2.ConversionRequest.SerializeToString,
            currency__converter__pb2.ConversionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
